import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import Provider from "@/store/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar />
        <main className="grid grid-rows-[repeat(10,_1fr)   bg-gradient-to-r from-slate-700 via-slate-800 to-slate-900 w-screen h-full">
          <Provider>{children}</Provider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
